### ISSUE TITLE
Plans for supporting the new point-buy eternal format?

### ISSUE THREAD

**Issue by gereons** [NetrunnerDB/netrunner-cards-json#599]
https://nisei.net/blog/revamp-of-the-eternal-format-21-11-released/

I'd like to support this in Net Deck, and like for all things Netrunner, a central source of truth for the underlying data would be great.
If there's interest, and no one beats me to it, it would contribute a JSON file with this data, structured somewhat along the lines of the current MWL and Rotation files.

**Comment by NoahTheDuke** [comment]
Thanks for offering! We have all of the data on hand already in [NoahTheDuke/netrunner-data](https://github.com/NoahTheDuke/netrunner-data) so that won't be necessary. The issue is making sure that however we do it doesn't blow up NRDB, lol. If you want, I can generate the json for you specifically and we can figure out how to integrate with nrdb later.

**Comment by gereons** [comment]
That would be awesome, thanks! Looking forward to it :)

**Comment by plural** [comment]
we have format, card pool and banlist files in the v2 folder for eternal now.  This is 100% gonna be an NRDB v2 thing, though.

**Comment by plural** [comment]
Gonna close this out as it is in progress and the support files are in the repo here.
